[cachyos.personal]
aur = [
  "anydesk-bin",
  "brave-bin",
  "cryptomator-bin",
  "cursor-bin",
  "ghostty",
  "jetbrains-toolbox",
  "mission-center",
  "obsidian",
  "rustdesk-bin",
  "slack-desktop",
  "spotify-launcher",
  "tinymediamanager",
  "vesktop",
  "whatsapp-for-linux",
  "whitesur-cursor-theme-git",
  "whitesur-gtk-theme",
  "whitesur-icon-theme",
  "whitesur-kde-theme",
  "xnviewmp",
  "yandex-disk",
  "zoom"
]
pacman = [
  "bleachbit",
  "calibre",
  "code",
  "fuzzel",
  "grim",
  "handbrake",
  "haruna",
  "hypridle",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "keepassxc",
  "keyd",
  "kio-gdrive",
  "kvantum",
  "libreoffice-fresh",
  "localsend",
  "nwg-dock-hyprland",
  "nwg-look",
  "qbittorrent",
  "signal-desktop",
  "simple-scan",
  "slurp",
  "swaync",
  "syncthing",
  "tailscale",
  "telegram-desktop",
  "torbrowser-launcher",
  "veracrypt",
  "vlc",
  "waybar",
  "wlogout",
  "swww",
  "wireguard-tools",
  "wl-clipboard",
  "xdg-desktop-portal-hyprland"
]