[darwin.common]
taps = [
  "homebrew/autoupdate"
]

[darwin.personal]
casks = [
  "anydesk",
  "appcleaner",
  "brave-browser",
  "calibre",
  "cursor",
  "ghostty",
  "google-drive",
  "handbrake-app",
  "iina",
  "iterm2",
  "jetbrains-toolbox",
  "keepassxc",
  "keka",
  "localsend",
  "maccy",
  "pearcleaner",
  "rectangle",
  "rustdesk",
  "onyx",
  "signal",
  "spotify",
  "syncthing-app",
  "telegram-desktop",
  "tinymediamanager",
  "tor-browser",
  "transmission",
  "veracrypt",
  "visual-studio-code",
  "vlc",
  "warp",
  "xnviewmp",
  "yandex-disk",
  "zoom",
  "stats",
  "macfuse"
]
mas = [
  {name = "Brother iPrint&Scan", id = 1193539993},
  {name = "Keynote", id = 409183694},
  {name = "Messenger", id = 1480068668},
  {name = "Numbers", id = 409203825},
  {name = "Pages", id = 409201541},
  {name = "Slack", id = 803453959},
  {name = "Tailscale", id = 1475387142},
  {name = "The Unarchiver", id = 425424353},
  {name = "WhatsApp", id = 310633997},
  {name = "Windows App", id = 1295203466},
  {name = "WireGuard", id = 1451685025},
  {name = "Xcode", id = 497799835}
]

[darwin.work]
