[packages.darwin.cloud]
"aws-cli" = {disabled = "headless", manager = "system", name = "awscli"}

[packages.darwin.common]
mas = {test = "mas version"}
openssh = {test = "$HOMEBREW_PREFIX/bin/ssh -V"}
"pinentry-mac" = {test = "pinentry-mac --version"}
"reattach-to-user-namespace" = {test = "reattach-to-user-namespace --version"}
zsh = {disabled = true}

[packages.darwin.docker]
colima = {test = "colima version"}
dive = {manager = "system", name = "dive"}
qemu = {test = "qemu-system-x86_64 --version"}

[packages.darwin.extra]
gocryptfs = {name = "gromgit/fuse/gocryptfs-mac"}

[packages.darwin.iac]
shellcheck = {manager = "system"}
sops = {manager = "system"}
terragrunt = {manager = "system"}
tflint = {manager = "system"}

[packages.darwin.kubernetes]
helm = {manager = "system"}
k3d = {manager = "system"}
k9s = {manager = "system"}
kubecolor = {manager = "system"}
kubectl = {manager = "system", name = "kubernetes-cli"}
kubectx = {manager = "system"}
kubens = {manager = "system", name = "kubectx"}
kubesess = {manager = "system", name = "kubesess"}
kustomize = {manager = "system"}
oc = {manager = "system", name = "openshift-cli"}
popeye = {manager = "system"}
stern = {manager = "system"}
yq = {manager = "system"}
